# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Kaman Phamdo
description: "Kaman Phamdo"
keywords: "Kaman, Phamdo, Blog, Portfolio"
url: http://kaman.phamdo.com/
baseurl: ""

google_analytics: UA-52446115-1
repo: http://github.com/phamdo.github.io
disqus_shortname: "kaman-phamdo"
disqus_site_shortname: "kaman-phamdo"

# Author settings
author:
  name: Kaman Phamdo
  job: Software Engineer

  #bio: "I am a software engineer and data enthusiast. I am passionate about journaling and documenting my experiences. I recently graduated from University of Maryland with degrees in Computer Science and Math."
  #bio: "software engineer, data enthusiast, life documenter, recent umd graduate"
  thumb: /images/author.gif
  email: mailto:kaman@phamdo.com
  url: https://kaman.phamdo.com/
  github: https://github.com/phamdo
  linkedin: https://linkedin.com/in/kphamdo
  instagram: https://instagram.com/kamanodomino
  resume: https://phamdo.github.io/resume.pdf

# navbar pages
navbar:
  - slug: portfolio
    title: Portfolio
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]

plugins:
    - jekyll-feed
