# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: "https://phamdo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Kaman Phamdo
description: "Personal Site"
keywords: 'kaman, phamdo, university of maryland, software engineer, computer science, math'
author:
  name: Kaman Phamdo
  job_title: Software Engineer
  location: College Park, MD
  email: kaman@phamdo.com
  social_links:
    - name: linkedin
      url: https://linkedin.com/in/kphamdo
    - name: github
      url: https://github.com/phamdo
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: <h1>Kaman Phamdo</h1>
  # section2:  
  #  <p>I am currently a fourth-year student at University of Maryland studying Computer Science and Math. On campus, I am an undergraduate researcher and teaching assistant in the computer science department. Previously, I was an intern at JHU Applied Physics Lab and JPMorgan Chase. After graduation, I will be working on research at UCLA's Institute for Pure and Applied Mathematics, and then starting my first "real job" as a software engineer in Pittsburgh, PA. My next goal is to get into grad school. I am passionate about journaling and documenting my experiences, which you can read about on my blog!</p>
  section3: <img src = "assets/images/profile-pic.png" width="300" height="300">
  section4: <div class="social-links">
      <a class="ico-rss btn" href="https://phamdo.github.io/blog" rel="me" target="_blank" title="Blog"></a>
              <a class="ico-gmail btn" href="mailto:kaman@phamdo.com" title="Email"></a>
              <a class="ico-linkedin btn" href="https://linkedin.com/in/kphamdo" title="LinkedIn"></a>
              <a class="ico-github btn" href="https://github.com/phamdo" title="GitHub"></a>
            </div>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: 
      <p>I am currently a fourth-year student at University of Maryland studying Computer Science and Math. 
      On campus, I am an undergraduate researcher and teaching assistant in the computer science department. 
      Previously, I was an intern at JHU Applied Physics Lab and JPMorgan Chase.
      After graduation, I will be working on research at UCLA's Institute for Pure and Applied Mathematics, 
      and then starting my first "real job" as a software engineer in Pittsburgh, PA. 
      My next goal is to get into grad school. 
      I am passionate about journaling and documenting my experiences, which you can read about on my blog!</p>

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_analytics: # e.g. 'UA-42456515-5'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
